#!/usr/bin/env python3
import requests
import feedparser
import random
import subprocess
import os
from datetime import datetime
from pathlib import Path
import pickle
import urllib.parse
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
from google.auth.exceptions import RefreshError

# ==================== HARDCODED CREDENTIALS ====================
BLOGGER_BLOG_ID = "6965563738161457805"
GOOGLE_CLIENT_ID = "405755279071-4vnbgocint5n006qj6i31e589q17l6un.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
# NEW REFRESH TOKEN FROM OAUTH PLAYGROUND
GOOGLE_REFRESH_TOKEN = "1//042r5ticcj42bcgYIAARAAGQSNwF-L9IrOeyFz0uhhBRdhHzzb3qLN5vJw3VE4K4bNJMo-J60qDYVsojjpfydin8jqMkXhvKJzAI20"

# ==================== SETUP ====================
CACHE_DIR = Path(".blog-cache")
CACHE_DIR.mkdir(exist_ok=True)
POSTS_DIR = Path("_posts")
POSTS_DIR.mkdir(exist_ok=True)

# ==================== POLLINATIONS.AI IMAGE ====================
def get_pollinations_image(topic_title, width=1024, height=576):
    """Get a free AI-generated image URL from Pollinations.ai"""
    try:
        prompt = f"Professional blog header image about {topic_title}, high quality, detailed, 4k, photorealistic"
        encoded = urllib.parse.quote(prompt)
        image_url = f"https://pollinations.ai/p/{encoded}?width={width}&height={height}&seed={random.randint(1,10000)}&nologo=true"
        return image_url
    except Exception as e:
        print(f"⚠️ Image generation error: {e}")
        return None

def create_image_html(title):
    """Generate HTML for the image at the top of the post"""
    image_url = get_pollinations_image(title)
    if image_url:
        return f'''
        <div style="margin-bottom: 30px; text-align: center;">
            <img src="{image_url}" alt="{title}" 
                 style="width:100%; max-width:800px; border-radius:12px; box-shadow:0 4px 20px rgba(0,0,0,0.15);">
            <p style="color:#777; font-size:0.8em; margin-top:8px;">🎨 AI-generated by Pollinations.ai</p>
        </div>
        '''
    return ''

# ==================== BLOGGER API ====================
def get_blogger_service():
    """Authenticate and return Blogger service."""
    try:
        creds = Credentials(
            token=None,
            refresh_token=GOOGLE_REFRESH_TOKEN,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=GOOGLE_CLIENT_ID,
            client_secret=GOOGLE_CLIENT_SECRET,
            scopes=["https://www.googleapis.com/auth/blogger"]
        )
        print("🔄 Refreshing access token...")
        creds.refresh(Request())
        print("✅ Token refreshed successfully.")
        service = build('blogger', 'v3', credentials=creds)
        return service
    except RefreshError as e:
        print(f"❌ Refresh token error: {e}")
        return None
    except Exception as e:
        print(f"❌ Unexpected auth error: {e}")
        return None

def post_to_blogger(title, content, labels=None):
    """Publish post to Blogger with an AI image"""
    if labels is None:
        labels = ['AI Generated', 'Trending']
    
    service = get_blogger_service()
    if not service:
        return False, "Authentication failed"
    
    # Add image at the top
    image_html = create_image_html(title)
    full_content = image_html + content.replace('\n', '<br>')
    
    post_body = {
        "kind": "blogger#post",
        "title": title,
        "content": f"""
        <div style="font-family: Arial, sans-serif; line-height:1.8; max-width:800px; margin:0 auto;">
            {full_content}
            <hr style="margin:40px 0 20px;">
            <p style="color:#666; font-style:italic;">Auto-generated on {datetime.now().strftime('%B %d, %Y')}</p>
        </div>
        """,
        "labels": labels
    }
    
    try:
        posts = service.posts()
        request = posts.insert(blogId=BLOGGER_BLOG_ID, body=post_body)
        print("📤 Sending request to Blogger API...")
        response = request.execute()
        print(f"✅ Post created! URL: {response.get('url')}")
        return True, response.get('url')
    except Exception as e:
        print(f"❌ Blogger API error: {e}")
        return False, str(e)

# ==================== TRENDING TOPICS ====================
def get_trending_topics():
    """Fetch from RSS feeds, fallback to static list if fails"""
    topics = []
    sources = [
        ('https://news.ycombinator.com/rss', 'Hacker News', 3),
        ('http://feeds.bbci.co.uk/news/rss.xml', 'BBC', 2),
        ('https://techcrunch.com/feed/', 'TechCrunch', 2),
        ('https://www.wired.com/feed/rss', 'Wired', 2),
        ('https://www.theverge.com/rss/index.xml', 'The Verge', 2)
    ]
    
    for url, name, limit in sources:
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:limit]:
                if entry.title and '[Removed]' not in entry.title:
                    topics.append({
                        'title': entry.title,
                        'description': entry.get('summary', '')[:200],
                        'source': name
                    })
        except Exception as e:
            print(f"⚠️ Error fetching {name}: {e}")
    
    # Always have fallbacks
    if not topics:
        topics = [
            {'title': 'The Future of AI in 2026', 'description': 'How artificial intelligence is transforming our world', 'source': 'Tech'},
            {'title': 'Climate Tech Innovations', 'description': 'Breakthroughs in green energy', 'source': 'Science'},
            {'title': 'Space Travel Updates', 'description': 'New missions to the Moon and Mars', 'source': 'Space'},
            {'title': 'Digital Privacy in the Modern Age', 'description': 'Protecting your data online', 'source': 'Security'},
            {'title': 'The Evolution of Remote Work', 'description': 'How work has changed forever', 'source': 'Business'}
        ]
    return topics

# ==================== OLLAMA GENERATION (with TinyLlama - faster) ====================
def generate_with_ollama(prompt, model="tinyllama"):
    """Generate text using local Ollama - using tinyllama for speed"""
    try:
        # Try API first
        response = requests.post('http://localhost:11434/api/generate',
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.7, 
                    "num_predict": 800  # Shorter for speed
                }
            },
            timeout=180  # 3 minutes
        )
        if response.status_code == 200:
            return response.json()['response'].strip()
    except Exception as e:
        print(f"⚠️ Ollama API error: {e}")
        # Fallback to CLI using absolute path
        try:
            result = subprocess.run(['/usr/local/bin/ollama', 'run', model, prompt],
                                   capture_output=True, text=True, timeout=180)
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception as e2:
            print(f"⚠️ Ollama CLI error: {e2}")
    
    # Ultimate fallback content
    return f"""
    <h2>Introduction</h2>
    <p>Today we're discussing an important topic that's been making waves recently: {prompt[:100]}...</p>
    
    <h2>Key Points</h2>
    <p>The developments in this area are worth paying attention to. Experts suggest that we'll see continued innovation and change throughout 2026.</p>
    
    <h2>Why This Matters</h2>
    <p>Understanding these trends helps us prepare for what's coming and make better decisions in our daily lives and work.</p>
    
    <h2>Conclusion</h2>
    <p>Stay tuned for more updates on this and other trending topics. The world is changing fast, and we're here to keep you informed.</p>
    """

def generate_blog_post(topic):
    """Generate a complete blog post using Ollama"""
    prompt = f"""Write a detailed blog post about:
Title: {topic['title']}
Description: {topic['description']}
Source: {topic['source']}

Write 300-400 words with:
- An engaging introduction
- 2-3 informative paragraphs
- A strong conclusion

Make it professional and interesting.
"""
    return generate_with_ollama(prompt)

# ==================== LOCAL BACKUP ====================
def save_local_post(title, content):
    """Save a local copy as markdown"""
    slug = title.lower().replace(' ', '-')[:50]
    # Remove any special characters
    slug = ''.join(c for c in slug if c.isalnum() or c == '-')
    filename = POSTS_DIR / f"{datetime.now().strftime('%Y-%m-%d')}-{slug}.md"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(f"# {title}\n\n{content}")
    print(f"💾 Saved locally: {filename}")
    return filename

# ==================== MAIN ====================
def main():
    print("="*60)
    print("🚀 AI Blogger with Pollinations.ai Images")
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*60)

    # 1. Get trending topics
    print("\n🔍 Fetching trending topics...")
    topics = get_trending_topics()
    chosen = random.choice(topics)
    print(f"🎯 Selected: {chosen['title']}")
    print(f"📌 Source: {chosen['source']}")

    # 2. Generate content with Ollama (TinyLlama for speed)
    print("\n✍️ Generating blog post with TinyLlama...")
    content = generate_blog_post(chosen)

    # 3. Always save a local backup
    local_file = save_local_post(chosen['title'], content)

    # 4. Post to Blogger with image
    print("\n📤 Posting to Blogger with AI image...")
    success, result = post_to_blogger(
        chosen['title'], 
        content,
        labels=['AI Generated', chosen['source'].replace(' ', '-'), 'Pollinations']
    )
    
    if success:
        print(f"\n✨ SUCCESS! Blog post is live!")
        print(f"🔗 {result}")
    else:
        print(f"\n⚠️ Blogger post failed, but local file saved: {local_file}")
        print(f"🔍 Error: {result}")

    print("\n✅ Job completed.")

if __name__ == "__main__":
    main()
