#!/usr/bin/env python3
"""
Blogger Auto-Poster with Falcon 7B – 1 post per run (3x daily)
- Fixed: Increased Falcon timeout to 600 seconds
- Fixed: Multiple image fallback methods
"""

import os
import sys
import requests
import feedparser
import random
import subprocess
import traceback
import urllib.parse
import time
import base64
from datetime import datetime
from pathlib import Path

# Google API imports
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
from google.auth.exceptions import RefreshError
from googleapiclient.errors import HttpError

# ==================== READ SECRETS ====================
BLOGGER_BLOG_ID = os.getenv("BLOGGER_BLOG_ID")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REFRESH_TOKEN = os.getenv("GOOGLE_REFRESH_TOKEN")

# ==================== CONFIG ====================
PRIMARY_MODEL = "falcon:7b"
FALLBACK_MODEL = "phi"
NUM_POSTS_PER_DAY = 1  # Changed to 1 (runs 3 times daily)

# ==================== SETUP ====================
CACHE_DIR = Path(".blog-cache")
POSTS_DIR = Path("_posts")
CACHE_DIR.mkdir(exist_ok=True)
POSTS_DIR.mkdir(exist_ok=True)

def log_error(step, error, details=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"\n❌ ERROR at {timestamp}")
    print(f"   Step: {step}")
    print(f"   Error: {error}")
    if details:
        print(f"   Details: {details}")
    print(f"   Traceback: {traceback.format_exc()}")

# ==================== MULTIPLE IMAGE SOURCES (FALLBACKS) ====================
def get_unsplash_image(topic_title):
    """Method 1: Unsplash random image (no API key needed for small usage)"""
    try:
        # Extract keywords (first 3 meaningful words)
        words = topic_title.split()[:3]
        keywords = ','.join(words)
        response = requests.get(
            f"https://source.unsplash.com/featured/800x400/?{keywords}",
            timeout=10,
            allow_redirects=False
        )
        if response.status_code == 302 and 'location' in response.headers:
            return response.headers['location']
    except:
        pass
    return None

def get_pollinations_image(topic_title):
    """Method 2: Pollinations.ai (free, no key needed) - FIXED URL"""
    try:
        prompt = f"Professional blog header image about {topic_title}, high quality, 4k"
        encoded = urllib.parse.quote(prompt)
        # Using the correct endpoint
        return f"https://image.pollinations.ai/prompt/{encoded}?width=1024&height=576&nologo=true"
    except:
        return None

def get_placeholder_image(topic_title):
    """Method 3: Generate a simple colored div with text (always works)"""
    colors = ['#667eea', '#764ba2', '#ff6b6b', '#4ecdc4', '#45b7d1']
    color = random.choice(colors)
    return f"PLACEHOLDER:{color}:{topic_title}"

def create_image_html(title):
    """Try multiple image sources in sequence"""
    
    # Try Unsplash first (most reliable for actual photos)
    unsplash_url = get_unsplash_image(title)
    if unsplash_url:
        return f'''
        <div style="margin-bottom:30px; text-align:center;">
            <img src="{unsplash_url}" alt="{title}"
                 style="width:100%; max-width:800px; height:400px; object-fit:cover; border-radius:12px; box-shadow:0 4px 20px rgba(0,0,0,0.15);">
            <p style="color:#777; font-size:0.8em;">📸 Photo from Unsplash</p>
        </div>
        '''
    
    # Try Pollinations next
    pollinations_url = get_pollinations_image(title)
    if pollinations_url:
        return f'''
        <div style="margin-bottom:30px; text-align:center;">
            <img src="{pollinations_url}" alt="{title}"
                 style="width:100%; max-width:800px; height:400px; object-fit:cover; border-radius:12px; box-shadow:0 4px 20px rgba(0,0,0,0.15);"
                 onerror="this.style.display='none'; this.nextElementSibling.style.display='block';">
            <div style="display:none; padding:20px; background:#f0f0f0; border-radius:12px;">
                <p>Image could not be loaded. Title: {title}</p>
            </div>
            <p style="color:#777; font-size:0.8em;">🎨 AI-generated by Pollinations.ai</p>
        </div>
        '''
    
    # Ultimate fallback - colored banner with emoji
    colors = ['#667eea', '#764ba2', '#ff6b6b', '#4ecdc4', '#45b7d1']
    color = random.choice(colors)
    return f'''
    <div style="margin-bottom:30px; text-align:center; background:{color}; padding:40px; border-radius:12px; color:white;">
        <span style="font-size:48px; display:block; margin-bottom:20px;">📰</span>
        <h3 style="margin:0; color:white;">{title}</h3>
        <p style="margin:10px 0 0; opacity:0.9;">Today's Featured Article</p>
    </div>
    '''

# ==================== BLOGGER AUTH ====================
def get_blogger_service():
    if not all([GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REFRESH_TOKEN]):
        print("❌ Missing Google credentials.")
        return None
    try:
        creds = Credentials(
            token=None,
            refresh_token=GOOGLE_REFRESH_TOKEN,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=GOOGLE_CLIENT_ID,
            client_secret=GOOGLE_CLIENT_SECRET,
            scopes=["https://www.googleapis.com/auth/blogger"]
        )
        print("🔄 Refreshing access token...")
        creds.refresh(Request())
        print("✅ Token refreshed.")
        service = build('blogger', 'v3', credentials=creds)
        blog_info = service.blogs().get(blogId=BLOGGER_BLOG_ID).execute()
        print(f"✅ Blog verified: {blog_info.get('name')}")
        return service
    except RefreshError as e:
        log_error("Token Refresh", str(e), "Generate new refresh token.")
        return None
    except Exception as e:
        log_error("Authentication", str(e))
        return None

def post_to_blogger(title, content, labels=None):
    if labels is None:
        labels = ['AI Generated', 'Trending']
    service = get_blogger_service()
    if not service:
        return False, "Auth failed"
    
    image_html = create_image_html(title)
    full_content = image_html + content.replace('\n', '<br>')
    
    post_body = {
        "kind": "blogger#post",
        "title": title,
        "content": f"""
        <div style="font-family:Arial,sans-serif; line-height:1.8; max-width:800px; margin:0 auto;">
            {full_content}
            <hr>
            <p style="color:#666; font-style:italic;">Auto-generated on {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}</p>
        </div>
        """,
        "labels": labels
    }
    
    try:
        response = service.posts().insert(blogId=BLOGGER_BLOG_ID, body=post_body).execute()
        print(f"✅ Post published: {response.get('url')}")
        return True, response.get('url')
    except HttpError as e:
        status = e.resp.status
        log_error("Blogger API", str(e), f"HTTP {status}")
        if status == 401:
            print("🔑 Token invalid – need new refresh token.")
        return False, str(e)
    except Exception as e:
        log_error("Blogger API", str(e))
        return False, str(e)

# ==================== FETCH TRENDING TOPICS ====================
def get_trending_topics():
    """Fetch topics from RSS feeds."""
    topics = []
    sources = [
        ('https://news.ycombinator.com/rss', 'Hacker News', 5),
        ('http://feeds.bbci.co.uk/news/rss.xml', 'BBC', 3),
        ('https://techcrunch.com/feed/', 'TechCrunch', 3),
        ('https://www.wired.com/feed/rss', 'Wired', 3),
        ('https://www.theverge.com/rss/index.xml', 'The Verge', 3)
    ]
    for url, name, lim in sources:
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries[:lim]:
                if entry.title and '[Removed]' not in entry.title:
                    topics.append({
                        'title': entry.title,
                        'description': entry.get('summary', '')[:200],
                        'source': name
                    })
        except Exception as e:
            log_error(f"RSS {name}", str(e))
    
    if not topics:
        # Fallback topics
        topics = [
            {'title': 'The Future of Artificial Intelligence', 'description': 'How AI is transforming our daily lives', 'source': 'Tech'},
            {'title': 'Climate Change Solutions', 'description': 'New innovations in green technology', 'source': 'Science'},
            {'title': 'Space Exploration Updates', 'description': 'Latest missions to Mars and beyond', 'source': 'Space'},
            {'title': 'Digital Privacy Tips', 'description': 'How to protect your data online', 'source': 'Security'},
            {'title': 'The Remote Work Revolution', 'description': 'How work has changed forever', 'source': 'Business'}
        ]
    random.shuffle(topics)
    return topics

# ==================== GENERATE WITH OLLAMA (INCREASED TIMEOUT) ====================
def generate_with_ollama(prompt, model=PRIMARY_MODEL):
    """Generate text using Ollama with 600 second timeout."""
    
    # Try API with increased timeout
    try:
        print(f"⏳ Generating with {model} (timeout: 600s)...")
        resp = requests.post('http://localhost:11434/api/generate',
                              json={
                                  "model": model, 
                                  "prompt": prompt, 
                                  "stream": False,
                                  "options": {
                                      "temperature": 0.7, 
                                      "num_predict": 1000,
                                      "top_k": 40,
                                      "top_p": 0.9
                                  }
                              },
                              timeout=600)  # Increased to 600 seconds (10 minutes)
        
        if resp.status_code == 200:
            content = resp.json().get('response', '').strip()
            if content:
                print(f"✅ Generation successful ({len(content)} chars)")
                return content
    except requests.exceptions.Timeout:
        print(f"⏰ {model} API timeout after 600 seconds")
    except Exception as e:
        print(f"⚠️ {model} API error: {e}")

    # Fallback to CLI with increased timeout
    try:
        print(f"🔄 Falling back to CLI with {model}...")
        result = subprocess.run(
            ['/usr/local/bin/ollama', 'run', model, prompt],
            capture_output=True, 
            text=True, 
            timeout=600  # 10 minutes
        )
        if result.returncode == 0:
            content = result.stdout.strip()
            if content:
                print(f"✅ CLI generation successful ({len(content)} chars)")
                return content
    except subprocess.TimeoutExpired:
        print(f"⏰ {model} CLI timeout after 600 seconds")
    except Exception as e:
        print(f"⚠️ {model} CLI error: {e}")

    # If primary fails, try fallback model
    if model != FALLBACK_MODEL:
        print(f"🔄 Falling back to {FALLBACK_MODEL}...")
        return generate_with_ollama(prompt, model=FALLBACK_MODEL)

    # Ultimate fallback content
    print("⚠️ Using emergency fallback content")
    return f"""
    <h2>Introduction</h2>
    <p>Today we're discussing an important topic: {prompt[:100]}...</p>
    
    <h2>Key Points</h2>
    <p>This topic has been generating significant discussion recently. Experts suggest that developments in this area will continue to evolve throughout 2026.</p>
    
    <h2>Why It Matters</h2>
    <p>Staying informed about current trends helps us understand the world around us and make better decisions.</p>
    
    <h2>Conclusion</h2>
    <p>Thank you for reading this automated post. We'll continue to monitor and report on important developments.</p>
    """

def generate_blog_post(topic):
    """Generate a blog post for a given topic."""
    prompt = f"""Write a detailed, engaging blog post about this topic:

TITLE: {topic['title']}
DESCRIPTION: {topic['description']}
SOURCE: {topic['source']}

Write 400-500 words with:
- An attention-grabbing introduction
- 3-4 informative paragraphs with specific details
- A strong conclusion that summarizes key points

Make it professional, interesting, and well-structured. Use proper paragraphs.

Blog Post:
"""
    return generate_with_ollama(prompt)

# ==================== LOCAL BACKUP ====================
def save_local_post(title, content):
    """Save a local copy of the post."""
    slug = title.lower().replace(' ', '-')[:50]
    slug = ''.join(c for c in slug if c.isalnum() or c == '-')
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = POSTS_DIR / f"{timestamp}_{slug}.md"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(f"# {title}\n\n{content}")
    print(f"💾 Local backup saved: {filename}")
    return filename

# ==================== MAIN ====================
def main():
    print("="*60)
    print("🚀 AI BLOGGER – Falcon 7B (1 post per run)")
    print(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*60)

    # Verify credentials
    missing = []
    if not BLOGGER_BLOG_ID: missing.append("BLOGGER_BLOG_ID")
    if not GOOGLE_CLIENT_ID: missing.append("GOOGLE_CLIENT_ID")
    if not GOOGLE_CLIENT_SECRET: missing.append("GOOGLE_CLIENT_SECRET")
    if not GOOGLE_REFRESH_TOKEN: missing.append("GOOGLE_REFRESH_TOKEN")
    if missing:
        print(f"❌ Missing secrets: {', '.join(missing)}")
        sys.exit(1)
    print("✅ All credentials present.")

    # Get topics
    topics = get_trending_topics()
    if not topics:
        print("❌ No topics available.")
        sys.exit(1)

    # Pick one random topic
    topic = random.choice(topics)
    print(f"\n🎯 Selected: {topic['title']} (from {topic['source']})")

    # Generate content
    print("\n✍️ Generating blog post with Falcon 7B (this may take 3-5 minutes)...")
    content = generate_blog_post(topic)
    
    # Save backup
    local_file = save_local_post(topic['title'], content)

    # Post to Blogger
    print("\n📤 Posting to Blogger with image...")
    success, result = post_to_blogger(
        topic['title'],
        content,
        labels=['AI Generated', topic['source'].replace(' ', '-'), 'Falcon7B']
    )

    # Summary
    print("\n" + "="*60)
    if success:
        print("✨ SUCCESS! Blog post published.")
        print(f"📌 URL: {result}")
        print(f"📁 Backup: {local_file}")
    else:
        print("⚠️ Blogger posting failed, but backup saved.")
        print(f"📁 Backup: {local_file}")
        print(f"🔍 Error: {result}")
    print("="*60)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n⚠️ Interrupted by user.")
        sys.exit(0)
    except Exception as e:
        log_error("Main execution", str(e))
        sys.exit(1)
